- hosts: 127.0.0.1
  connection: local
  tasks:
   - name: Create Linode Server
      include_role:
        name: create-linode-server
  
    - name: Add the IP of newely created server
      add_host:
        name: "{{ created_linode['instance']['ipv4'] }}"
        groups: "{{ hosts_group }}"