- hosts: test
  remote_user: enuma
  become: True
  vars_files:
    - "required-vars.yml"
  tasks:
    - name: Create User that will handle running the app and deploy updates
      include_role:
        name: create-deployer-user