- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add the IP of newely created server
      add_host:
        name: "12.12.121.1"
        groups: "linode_group"
    - name: Debug the creation output
      debug:
        var: hostvars['127.0.0.1']