- name: Create deployment user
  user:
    name: "{{ deployer_user }}"
    shell: /sbin/nologin
  register: deployer_created

- name: Add ssh key
  authorized_key:
    user: "{{ deployer_user }}"
    key: "{{ lookup('file', 'ssh-keys/macair-fat7y.pub') }}"
    state: present

- name: "Ensures /home/{{ deployer_user }} exists"
  file:
    path: "/home/{{ deployer_user }}"
    state: directory
    owner: "{{ deployer_user }}"
    group: "{{ deployer_group }}"

- name: "Set proper acl flags for {{ deployer_user }}"
  acl:
    path: "/home/{{ deployer_user }}"
    entry: "u:{{ deployer_user }}:rwx"
    state: present
    recursive: yes
    default: yes

- name: set proper acl flags for www-data group
  acl:
    path: "/home/{{ deployer_user }}"
    entry: "g:{{ deployer_group }}:rx"
    state: present
    recursive: yes
    default: yes

- name: "Ensures {{ project_location }} exists"
  file:
    path: "{{ project_location }}"
    state: directory
    group: "{{ deployer_group }}"
    owner: "{{ deployer_user }}"

- name: "Ensure permissions on /home/{{ deployer_user }}"
  shell: chmod 2750 -R /home/{{ deployer_user }}

- name: "Ensure /home/{{ deployer_user }}/.ssh exists"
  file:
    path: "/home/{{ deployer_user }}/.ssh"
    state: directory
    owner: "{{ deployer_user }}"
  
- name: Copy deployer private key to remote machine
  copy:
    src: deployer_user
    dest: "/home/{{ deployer_user }}/.ssh/id_rsa"
    mode: 0400
    group: "{{ deployer_user }}"
    owner: "{{ deployer_user }}"

- name: Copy deployer public key to remote machine
  copy:
    src: "{{ deployer_user }}.pub"
    dest: "/home/{{ deployer_user }}/.ssh/id_rsa.pub"
    mode: 0644
    group: "{{ deployer_user }}"
    owner: "{{ deployer_user }}"