- name: Add site file for test.kanshoubakuya.com
  template:
    src: site.j2
    dest: /etc/nginx/sites-available/test.kanshoubakuya.com
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Link test.kanshoubakuya.com in /etc/nginx/sites-enabled
  file:
    src: /etc/nginx/sites-available/test.kanshoubakuya.com
    dest: /etc/nginx/sites-enabled/test.kanshoubakuya.com
    state: link