- name: "Add site file for {{ domain_name }}"
  template:
    src: site.j2
    dest: "/etc/nginx/sites-available/{{ domain_name }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: "Link {{ domain_name }} in /etc/nginx/sites-enabled"
  file:
    src: "/etc/nginx/sites-available/{{ domain_name }}"
    dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
    state: link