- name: Install python-software-properties package
  apt:
    pkg: python-software-properties
    state: latest

- name: add ppa:ondrej/php repository
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: Install php-7.1
  apt:
    name: php7.1
    state: latest
    update_cache: yes

- name: Install php modules
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php7.1-mysql
    - php7.1-curl
    - php7.1-json
    - php7.1-fpm
    - php7.1-opcache
    - php7.1-mbstring
    - php7.1-xml